version: '3.1'

services:
  front:
    container_name: web-front-container
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/home/root
    ports:
      - 8081:8080
    restart: on-failure


